name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Check
        if: github.event_name == 'push'
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
      - uses: giraffate/clippy-action@v1
        if: github.event_name == 'pull_request'
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
